### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by milqnomadu** [yikuansun/HeadlessPhotopea#1]
Does this work?

**Comment by yikuansun** [comment]
Yep, lemme know what kind of project you're trying to make and I can help you set it up!

**Comment by milqnomadu** [comment]
Hi Yikun, thank you so much for your response. I was trying to create a script that was able to take a set of images from a given local folder and replace them one by one inside of the only smart object layer of a psd from a given local folder. To then export each time as a webp with the name of the given image inside a given output folder

**Comment by yikuansun** [comment]
@milqnomadu Awesome, this should be decently simple

Set up an npm project and install HeadlessPhotopea. You can then create a new instance of HeadlessPhotopea (I'd recommend setting `showBrowser` to `true` for testing, as you will be able to see the browser window working):
```js
import HeadlessPhotopea from "headlessphotopea";

let pea = new HeadlessPhotopea({ showBrowser: true, });
```
Now, `pea` is the object on which you can call the methods shown in [docs](https://github.com/yikuansun/HeadlessPhotopea/blob/master/docs.md). For example, you can now open your PSD file using `addBinaryAsset`:
```js
import { readFileSync, writeFileSync } from "fs";

let psd = readFileSync("absolute_path_to_psd_file");
await pea.addBinaryAsset(asset); // make sure to use await because it is asynchronous. This is why using a module type package would be better than commonjs here
```
Now let's say you've stored all of your images as Data URLs in an array called `imgs` (you can do this with readdir and readfilesync (base64, then add the data: prefix)), now you can loop through those:
```js
// precondition: imgs contains all of the images as data urls
// you lowkey need some photoshop scripting knowledge for this part so make sure to look it up if you haven't already

// call the main document "main"
await pea.runScript(`app.activeDocument.name = "main";`);
// open up the smart object into a new document
await pea.runScript(`app.activeDocument.activeLayer = app.activeDocument.layers.getByName("name_of_smart_obj_layer");`);
await pea.runScript(`executeAction(stringIDToTypeID("placedLayerEditContents"));`);
// rename the smart object doucment
await pea.runScript(`app.activeDocument.name = "smartObj";`);
// now you can navigate back and forth between main and smartObj :)

let i = 0; // make sure each outputted file has a unique filename

for (let img of imgs) {
    // go to smart object (make sure you add .psd when you use getByName)
    await pea.runScript(`app.activeDocument = app.documents.getByName("smartObj.psd");`);
    // open your image
    await pea.openFromURL(img);
    // get rid of other layers in the smart object (easiest way is to flatten image but this does not always work, you might have to come up with another script for this)
    await pea.runScript(`app.activeDocument.flatten();`);

    // save smart object and go back to main document
    await pea.runScript(`
        app.activeDocument.save();
        app.activeDocument = app.documents.getByName("main.psd");
    `);

    // get output image buffer
    let buff = await pea.exportImage("webp");
    
    // now you can output result as an image
    writeFileSync("output_path/" + i + ".webp", buff);

    i++; // increment
}
```
That's basically it, see if you can implement that. Lemme know if I made any mistakes or if I should clarify anything further. Feel free to send me your repository and I can fork it and demo if you want. Lemme know how it goes!

Edit: fixed some bugs and used new methods from v1.1.0 (released today)

**Comment by milqnomadu** [comment]
Thank you so much Yikun!

**Comment by milqnomadu** [comment]
Hey @yikuansun , would it be possible to contact via email? my email is milqnomadu@gmail.com. thanks and merry christmas

**Comment by yikuansun** [comment]
@milqnomadu Just emailed. Merry Christmas!
